<?php
/**
 * Copyright (c) 2017 - present
 * LaravelCaptcha - CaptchaConfigurationTest.php
 * author: Roberto Belotti - roby.belotti@gmail.com
 * web : robertobelotti.com, github.com/biscolab
 * Initial version created on: 13/2/2019
 * MIT license: https://github.com/biscolab/laravel-recaptcha/blob/master/LICENSE
 */

namespace Nopal\Captcha\Tests;

use Nopal\Captcha\Captcha;

/**
 * Class CaptchaConfigurationTest
 * @package Nopal\Captcha\Tests
 */
class CaptchaConfigurationTest extends TestCase
{

	/**
	 * @var Captcha
	 */
	protected $captcha;

    /**
	 * @var Captcha
	 */
    protected $recaptcha;

    /**
	 * @var Captcha
	 */
    protected $turnstile;

	/**
	 * @test
	 */
	public function testGetApiSiteKey() {
		$this->assertEquals("api_site_key", $this->recaptcha->getApiSiteKey());
		$this->assertEquals("api_site_key", $this->turnstile->getApiSiteKey());
	}

	/**
	 * @test
	 */
	public function testGetApiSecretKey() {
		$this->assertEquals("api_secret_key", $this->recaptcha->getApiSecretKey());
		$this->assertEquals("api_secret_key", $this->turnstile->getApiSecretKey());
	}

	/**
	 * @test
	 */
	public function testSkipIpWhiteListIsArray()
	{

		$ip_whitelist = $this->captcha->getIpWhitelist();
		$this->assertTrue(is_array($ip_whitelist));
		$this->assertCount(2, $ip_whitelist);

		$this->assertEquals('10.0.0.1', $ip_whitelist[0]);
		$this->assertEquals('10.0.0.2', $ip_whitelist[1]);
	}

	/**
	 * @test
	 */
	public function testCurlTimeoutIsSet()
	{

		$this->assertEquals(3, $this->captcha->getCurlTimeout());
	}

	/**
	 * Define environment setup.
	 *
	 * @param  \Illuminate\Foundation\Application $app
	 *
	 * @return void
	 */
	protected function getEnvironmentSetUp($app)
	{

		$app['config']->set('captcha.turnstile.site_key', 'api_site_key');
		$app['config']->set('captcha.turnstile.secret_key', 'api_secret_key');
		$app['config']->set('captcha.recaptcha.site_key', 'api_site_key');
		$app['config']->set('captcha.recaptcha.secret_key', 'api_secret_key');
		$app['config']->set('captcha.version', 'turnstile');
		$app['config']->set('captcha.skip_ip', '10.0.0.1,10.0.0.2');
		$app['config']->set('captcha.curl_timeout', 3);
	}

	/**
	 * Setup the test environment.
	 */
	protected function setUp(): void
	{

		parent::setUp(); // TODO: Change the autogenerated stub

		$this->captcha = captcha();
        $this->recaptcha = new Captcha('recaptcha_v2');
        $this->turnstile = new Captcha('turnstile');
	}
}